ENT.Type = "anim"
ENT.Base = "test_base"
 
ENT.PrintName		= "GOD Printer"
ENT.Author			= "[RG]Uggleking"
ENT.Contact			= "Don't"
ENT.Purpose			= "Make it rain baby"
ENT.Instructions	= "Use with care. Always handle with gloves."
ENT.Category 		= "Printers"
ENT.Delay 			= 20
ENT.PayLow			= 10000
ENT.PayHigh 		= 12000
ENT.PowerUsage		= 1
ENT.Price 			= 3200000
ENT.Spawnable 		= true
ENT.Basewars 		= true
ENT.MaxHealth 		= 200
ENT.Buyer 			= "WHYYY"
ENT.PrintColor 		= Color(167, 91, 16, 255)
ENT.Flip 			= false
ENT.Model 			= "models/props_lab/reciever01b.mdl"